base_url = "https://eneskemalergin.github.io"
default_language = "en"
title = "Enes K. Ergin"
compile_sass = true

[[taxonomies]]
name = "tags"
paginate_by = 10

[extra]
name = "Enes K. Ergin, PhD"

menu = [
    { name = "Home", url = "/" },
    { name = "Projects", url = "/projects/" },
    { name = "Research", url = "/research/" },
    { name = "Blog", url = "/blog/" },
    { name = "CV", url = "https://raw.githubusercontent.com/eneskemalergin/My_CV/master/Full_CV_Resonance.pdf" },
]

[[extra.social]]
name = "E-Mail"
url = "mailto:eneskemalergin@gmail.com"
icon = "fas fa-envelope"

[[extra.social]]
name = "LinkedIn"
url = "https://linkedin.com/in/eneskemalergin"
icon = "fab fa-linkedin"

[[extra.social]]
name = "GitHub"
url = "https://github.com/eneskemalergin"
icon = "fab fa-github"

[[extra.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=6iZzHecAAAAJ"
icon = "ai ai-google-scholar"

[[extra.social]]
name = "ORCID"
url = "https://orcid.org/0000-0001-9810-7399"
icon = "ai ai-orcid"
